/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package component.muaSachComponent;

import bus.ChiTietHoaDonBUS;
import bus.HoaDonBUS;
import bus.SachBUS;
import component.ToolBarAndTableBanSach;
import dto.ChiTietHoaDonDTO;
import dto.HoaDonDTO;
import dto.SachDTO;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mansh
 */
public class ThanhToanMuaSach extends javax.swing.JDialog {

    private HoaDonDTO hd;
    private ArrayList<ChiTietHoaDonDTO> cthdList;
    private ToolBarAndTableBanSach tbs;

    /**
     * Creates new form NewJDialog
     */
    public ThanhToanMuaSach(java.awt.Frame parent, boolean modal, HoaDonDTO hd, ArrayList<ChiTietHoaDonDTO> cthdList, ToolBarAndTableBanSach tbs) {
        super(parent, modal);
        this.hd = hd;
        this.cthdList = cthdList;
        this.tbs = tbs;
        initComponents();
        tienThanhToanLbl.setText(hd.getTongTien() + "");
    }

    private int addCTHD() {
        for (ChiTietHoaDonDTO cthd : cthdList) {
            int result = ChiTietHoaDonBUS.getInstance().add(cthd);
            if (result <= 0) {
                return 0;
            }
        }
        return 1;
    }

    private void updateSachInDB() {
        for (SachDTO s : tbs.getListS()) {
            SachBUS.getInstance().update(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tienDuaTxt = new javax.swing.JTextField();
        thanhToanBtn = new javax.swing.JButton();
        tienThanhToanLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Số tiền cần thanh toán: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Số tiền khách đưa: ");

        tienDuaTxt.setPreferredSize(new java.awt.Dimension(200, 24));

        thanhToanBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thanhToanBtn.setText("Thanh toán");
        thanhToanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thanhToanBtnMouseClicked(evt);
            }
        });
        thanhToanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Huỷ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tienThanhToanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tienDuaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(thanhToanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(tienThanhToanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tienDuaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thanhToanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thanhToanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thanhToanBtnMouseClicked
        if (tienDuaTxt.getText().isEmpty() || tienDuaTxt.getText() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào số tiền khách đã đưa!", "Thất bại", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Double.parseDouble(tienDuaTxt.getText()) < hd.getTongTien()) {
                JOptionPane.showMessageDialog(this, "Tiền đưa còn thiếu " + (hd.getTongTien() - Double.parseDouble(tienDuaTxt.getText())), "Thất bại", JOptionPane.ERROR_MESSAGE);
            } else {
                int result = HoaDonBUS.getInstance().add(hd);
                if (result > 0) {
                    int resultCTHD = addCTHD();
                    if (resultCTHD == 1) {
                        JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thành công!", JOptionPane.INFORMATION_MESSAGE);

                        // Định dạng số tiền thối lại
                        double tienThoiLai = Double.parseDouble(tienDuaTxt.getText()) - hd.getTongTien();
                        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
                        String tienThoiLaiFormatted = currencyFormat.format(tienThoiLai);

                        JOptionPane.showMessageDialog(this, "Thối lại khách " + tienThoiLaiFormatted, "Success", JOptionPane.INFORMATION_MESSAGE);
                        updateSachInDB();
                        tbs.getJTab().setSelectedIndex(0);
                        tbs.refrestTableData();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Thanh toán thất bại, lỗi hệ thống!", "Thất bại", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Thanh toán thất bại, lỗi hệ thống!", "Thất bại", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_thanhToanBtnMouseClicked

    private void thanhToanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thanhToanBtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton thanhToanBtn;
    private javax.swing.JTextField tienDuaTxt;
    private javax.swing.JLabel tienThanhToanLbl;
    // End of variables declaration//GEN-END:variables
}
