/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package component.sachcomponent;

import bus.NhaXuatBanBUS;
import bus.SachBUS;
import bus.TacGiaBUS;
import component.ToolBarAndTableSach;
import dto.NhaXuatBanDTO;
import dto.SachDTO;
import dto.TacGiaDTO;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mansh
 */
public class UpdateSach extends javax.swing.JDialog {

    private String linkAnh;
    private SachDTO selectedSach;
    private ToolBarAndTableSach tblSach;

    /**
     * Creates new form UpdateSach
     *
     * @param parent
     * @param modal
     * @param tblSach
     */
    public UpdateSach(JFrame parent, boolean modal, ToolBarAndTableSach tblSach) {
        super(parent, modal);
        this.tblSach = tblSach;
        initComponents();
        ArrayList<NhaXuatBanDTO> nxbList = NhaXuatBanBUS.getInstance().getAll();
        ArrayList<TacGiaDTO> tgList = TacGiaBUS.getInstance().getAll();

        for (NhaXuatBanDTO nxb : nxbList) {
            maNxbComboBox.addItem(nxb.getMaNXB() + ": " + nxb.getTen());
        }

        for (TacGiaDTO tg : tgList) {
            maTgComboBox.addItem(tg.getMaTacGia() + ": " + tg.getTen());
        }
        this.pack();
        showOldValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namXuatBanFld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        huySachBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        updateSachBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        soLuongFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        giaNhapFld = new javax.swing.JTextField();
        maTgComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        maNxbComboBox = new javax.swing.JComboBox<>();
        giaBanFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tenSachFld = new javax.swing.JTextField();
        theLoaiFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        previewImg = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(593, 388));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Thể loại");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Năm xuất bản");

        huySachBtn.setBackground(new java.awt.Color(102, 102, 102));
        huySachBtn.setForeground(new java.awt.Color(255, 255, 255));
        huySachBtn.setText("Huỷ");
        huySachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huySachBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã tác giả");

        updateSachBtn.setBackground(new java.awt.Color(102, 255, 0));
        updateSachBtn.setText("Thay đổi");
        updateSachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSachBtnMouseClicked(evt);
            }
        });
        updateSachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSachBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã NXB");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng");

        maTgComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giá nhập");

        maNxbComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên sách");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giá bán");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ảnh");

        previewImg.setText("Preview Image");
        previewImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setText("Chọn ảnh");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateSachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(huySachBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(previewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addGap(17, 17, 17)))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(soLuongFld, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(namXuatBanFld, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(tenSachFld, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(maTgComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maNxbComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(45, 45, 45)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(giaBanFld)
                                .addComponent(giaNhapFld)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(theLoaiFld, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGap(6, 6, 6)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(previewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateSachBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(huySachBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(giaNhapFld, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(giaBanFld)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(52, 52, 52))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(theLoaiFld, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(52, 52, 52))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tenSachFld, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namXuatBanFld)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(maTgComboBox))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(maNxbComboBox))))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(soLuongFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGap(118, 118, 118)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huySachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huySachBtnMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_huySachBtnMouseClicked
    private void getSelectedTacGiaSelected(String maTG) {
        for (int i = 0; i < maTgComboBox.getItemCount(); i++) {
            String item = maTgComboBox.getItemAt(i);
            if (item.startsWith(maTG)) {
                maTgComboBox.setSelectedIndex(i);
                return;
            }
        }
    }

    private void getSelectedNXBSelected(String maNXB) {
        for (int i = 0; i < maNxbComboBox.getItemCount(); i++) {
            String item = maNxbComboBox.getItemAt(i);
            if (item.startsWith(maNXB)) {
                maNxbComboBox.setSelectedIndex(i);
                return;
            }
        }
    }

    private void showOldValue() {
        String idSach = tblSach.getSelectedItemId();
        SachDTO s = new SachDTO();
        s.setMaSach(idSach);
        this.selectedSach = SachBUS.getInstance().getById(s);
        tenSachFld.setText(selectedSach.getTenSach());
        namXuatBanFld.setText(selectedSach.getNamXuatBan() + "");

        String maTG = selectedSach.getMaTacGia();
        String maNXB = selectedSach.getMaNXB();
        getSelectedTacGiaSelected(maTG);
        getSelectedNXBSelected(maNXB);

        soLuongFld.setText(selectedSach.getSoLuong() + "");
        giaNhapFld.setText(selectedSach.getGiaNhap() + "");
        giaBanFld.setText(selectedSach.getGiaBan() + "");
        theLoaiFld.setText(selectedSach.getTheLoai());

        File imageFile = new File("D:\\Work Space\\doAn\\doAnJava\\quanlycuahangsach\\src\\main\\java\\icon\\" + selectedSach.getPhoto());
        if (imageFile.exists()) {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(imageFile.getAbsolutePath()).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
            previewImg.setText("");
            previewImg.setIcon(imageIcon);
        } else {
            // Xử lý nếu tệp không tồn tại
            previewImg.setText("Ảnh không tồn tại");
        }
    }
    private void updateSachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSachBtnMouseClicked
        String tenSach = tenSachFld.getText();
        String namXuatBan = namXuatBanFld.getText();

        String maTacGia = "";
        String maNXB = "";

        if (maTgComboBox.getSelectedIndex() > 0) {
            String tgTxt = (String) maTgComboBox.getSelectedItem();
            String[] maTgArray = tgTxt.split(":");
            maTacGia = maTgArray[0];
        }

        if (maNxbComboBox.getSelectedIndex() > 0) {
            String nxbTxt = (String) maNxbComboBox.getSelectedItem();
            String[] maNXBArray = nxbTxt.split(":");
            maNXB = maNXBArray[0];
        }

        String soLuong = soLuongFld.getText();
        String giaNhap = giaNhapFld.getText();
        String giaBan = giaBanFld.getText();
        String theLoai = theLoaiFld.getText();
        String photo = this.linkAnh;

        String errors = SachBUS.getInstance().validateData(tenSach, namXuatBan, maTacGia, maNXB, soLuong, giaNhap, giaBan, theLoai, photo);
        if (errors == null || errors.isEmpty()) {
            SachDTO s = SachBUS.getInstance().createUpdatedSach(this.selectedSach.getMaSach(), tenSach, namXuatBan, maTacGia, maNXB, soLuong, giaNhap, giaBan, theLoai, photo);
            System.out.println(s);
            int result = SachBUS.getInstance().update(s);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật sách thành công!", "Thành công!", JOptionPane.INFORMATION_MESSAGE);
                tblSach.refreshDataListS();
                tblSach.loadDataSach(tblSach.getListS());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật sách thất bại, lỗi hệ thống!", "Thất bại", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, errors, "Cập nhật sách thất bại!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_updateSachBtnMouseClicked

    private void updateSachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSachBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateSachBtnActionPerformed

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(previewImg.getWidth(), previewImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private File getUniqueFile(File file) {
        if (!file.exists()) {
            return file;
        }
        String name = file.getName();
        String parent = file.getParent();
        String baseName = name.substring(0, name.lastIndexOf('.'));
        String extension = name.substring(name.lastIndexOf('.'));
        int i = 1;
        while (true) {
            File newFile = new File(parent + File.separator + baseName + "_" + i + extension);
            if (!newFile.exists()) {
                return newFile;
            }
            i++;
        }
    }


    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        JFileChooser fc = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", "img", "png");
        fc.setFileFilter(imageFilter);

        int returnVal = fc.showOpenDialog(this); // hiển thị hộp thoại chọn tệp để mở trên this.view

        if (returnVal == JFileChooser.APPROVE_OPTION) { // Nếu người dùng chọn Open
            File selectedFile = fc.getSelectedFile();
            File destinationFile;

            // Kiểm tra xem tệp được chọn có nằm trong thư mục của dự án hay không
            if (selectedFile.getAbsolutePath().contains(System.getProperty("user.dir"))) {
                // Tệp được chọn nằm trong thư mục của dự án
                destinationFile = selectedFile;
            } else {
                // Tệp được chọn nằm ngoài thư mục của dự án, sao chép vào thư mục ./src/icon/
                destinationFile = new File("./src/icon/" + selectedFile.getName());
                destinationFile = getUniqueFile(destinationFile); // Lấy tên tệp duy nhất
                try {
                    Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Không thể sao chép tệp.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Hiển thị hình ảnh xem trước
            if (imageFilter.accept(destinationFile)) {
                try (FileInputStream fis = new FileInputStream(destinationFile)) {
                    this.previewImg.setIcon(new ImageIcon(ImageIO.read(fis)));
                    this.linkAnh = destinationFile.getName();
                } catch (IOException e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Không thể đọc tệp.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chỉ mở được định dạng file .img, .png", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (returnVal == JFileChooser.CANCEL_OPTION) { // Nếu người dùng chọn Cancel
            // Xử lý khi người dùng chọn Cancel (nếu cần)
        }
    }//GEN-LAST:event_jButton4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField giaBanFld;
    private javax.swing.JTextField giaNhapFld;
    private javax.swing.JButton huySachBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> maNxbComboBox;
    private javax.swing.JComboBox<String> maTgComboBox;
    private javax.swing.JTextField namXuatBanFld;
    private javax.swing.JLabel previewImg;
    private javax.swing.JTextField soLuongFld;
    private javax.swing.JTextField tenSachFld;
    private javax.swing.JTextField theLoaiFld;
    private javax.swing.JButton updateSachBtn;
    // End of variables declaration//GEN-END:variables
}
