/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package component.nhapSachComponent;

import bus.NhaXuatBanBUS;
import bus.SachBUS;
import bus.TacGiaBUS;
import component.ToolBarAndTableNhapSach;
import dto.NhaXuatBanDTO;
import dto.SachDTO;
import dto.TacGiaDTO;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mansh
 */
public class AddNewSach extends javax.swing.JDialog {

    private ToolBarAndTableNhapSach tblSach;
    private String linkAnh;

    /**
     * Creates new form AddNewSach
     */
    public AddNewSach(java.awt.Frame parent, boolean modal, ToolBarAndTableNhapSach tblSach) {
        super(parent, modal);
        initComponents();
        this.tblSach = tblSach;
        setupNumericField(giaBanFld);
        setupNumericField(giaNhapFld);

        ArrayList<NhaXuatBanDTO> nxbList = NhaXuatBanBUS.getInstance().getAll();
        ArrayList<TacGiaDTO> tgList = TacGiaBUS.getInstance().getAll();

        for (NhaXuatBanDTO nxb : nxbList) {
            if (nxb.getTrangThai() == 1) {
                maNXBCbx.addItem(nxb.getMaNXB() + ": " + nxb.getTen());
            }
        }

        for (TacGiaDTO tg : tgList) {
            if (tg.getTrangThai() == 1) {
                maTacGiaCbx.addItem(tg.getMaTacGia() + ": " + tg.getTen());
            }
        }
        pack();
    }

    private void setupNumericField(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();  // Ngăn không cho nhập các ký tự không phải là số
                }
            }
        });
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(previewImg.getWidth(), previewImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tenSachFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        giaNhapFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namXuatBanFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        giaBanFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maTacGiaCbx = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        theLoaiFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maNXBCbx = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        previewImg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cancelSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        saveSach = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 300));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 0, 12));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên sách");
        jPanel1.add(jLabel1);

        tenSachFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenSachFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSachFldActionPerformed(evt);
            }
        });
        jPanel1.add(tenSachFld);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Giá nhập");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel1.add(jLabel2);

        giaNhapFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(giaNhapFld);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Năm xuất bản");
        jPanel1.add(jLabel3);

        namXuatBanFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namXuatBanFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namXuatBanFldActionPerformed(evt);
            }
        });
        jPanel1.add(namXuatBanFld);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá bán");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel1.add(jLabel4);

        giaBanFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(giaBanFld);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã tác giả");
        jPanel1.add(jLabel5);

        maTacGiaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định" }));
        jPanel1.add(maTacGiaCbx);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Thể loại");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel1.add(jLabel6);

        theLoaiFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(theLoaiFld);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã NXB");
        jPanel1.add(jLabel7);

        maNXBCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định" }));
        jPanel1.add(maNXBCbx);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Chọn ảnh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        cancelSave.setBackground(new java.awt.Color(102, 102, 102));
        cancelSave.setText("Huỷ");
        cancelSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cancelSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelSave, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        saveSach.setBackground(new java.awt.Color(102, 255, 0));
        saveSach.setText("Lưu");
        saveSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveSachMouseClicked(evt);
            }
        });
        saveSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveSachKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(saveSach, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveSach, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namXuatBanFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namXuatBanFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namXuatBanFldActionPerformed

    private void tenSachFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSachFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSachFldActionPerformed

    private void cancelSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelSaveActionPerformed

    private void saveSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveSachKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveSachKeyPressed

    private void saveSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveSachMouseClicked
        String tenSach = tenSachFld.getText();
        String namXuatBan = namXuatBanFld.getText();
        String maTacGia = "";
        String maNXB = "";

        if (maTacGiaCbx.getSelectedIndex() > 0) {
            String tgTxt = (String) maTacGiaCbx.getSelectedItem();
            String[] maTgArray = tgTxt.split(":");
            maTacGia = maTgArray[0];
        }

        if (maNXBCbx.getSelectedIndex() > 0) {
            String nxbTxt = (String) maNXBCbx.getSelectedItem();
            String[] maNXBArray = nxbTxt.split(":");
            maNXB = maNXBArray[0];
        }

        String soLuong = "0";
        String giaNhap = giaNhapFld.getText();
        String giaBan = giaBanFld.getText();
        String theLoai = theLoaiFld.getText();
        String photo = this.linkAnh;

        String errors = SachBUS.getInstance().validateData(tenSach, namXuatBan, maTacGia, maNXB, soLuong, giaNhap, giaBan, theLoai, photo);
        if (errors == null || errors.isEmpty()) {
            SachDTO s = SachBUS.getInstance().createNewSach(tenSach, namXuatBan, maTacGia, maNXB, soLuong, giaNhap, giaBan, theLoai, photo);
            int result = SachBUS.getInstance().add(s);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Thêm sách thành công!", "Thành công!", JOptionPane.INFORMATION_MESSAGE);
                tblSach.refreshDataListS();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sách thất bại, lỗi hệ thống!", "Thất bại", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, errors, "Thêm sách thất bại", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveSachMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this); // hiển thị hộp thoại chọn tệp để mở trên this.view
        if (returnVal == JFileChooser.APPROVE_OPTION) { // Nếu người dùng chọn Open
            File file = fc.getSelectedFile();
            if (file.getName().endsWith(".img") || file.getName().endsWith(".png")) {
                try {
                    this.previewImg.setIcon(ResizeImage(file.getAbsolutePath()));
                    this.linkAnh = file.getName();
                } catch (Exception e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chỉ mở được định dạng file .jpg, .png", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else if (returnVal == JFileChooser.CANCEL_OPTION) { // Nếu người dùng chọn Cancel

        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSave;
    private javax.swing.JTextField giaBanFld;
    private javax.swing.JTextField giaNhapFld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> maNXBCbx;
    private javax.swing.JComboBox<String> maTacGiaCbx;
    private javax.swing.JTextField namXuatBanFld;
    private javax.swing.JLabel previewImg;
    private javax.swing.JButton saveSach;
    private javax.swing.JTextField tenSachFld;
    private javax.swing.JTextField theLoaiFld;
    // End of variables declaration//GEN-END:variables
}
