/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package component.nhapSachComponent;

import bus.NhaCungCapBUS;
import component.ToolBarAndTableNhapSach;
import dto.NhaCungCapDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author mansh
 */
public class ChooseNCC extends javax.swing.JDialog {

    private ToolBarAndTableNhapSach tblNhapSach;
    private JTabbedPane jTabbedPane1;

    /**
     * Creates new form ChooseNCC
     */
    public ChooseNCC(java.awt.Frame parent, boolean modal, ToolBarAndTableNhapSach tblNhapSach, JTabbedPane jTabbedPane1) {
        super(parent, modal);
        initComponents();
        this.tblNhapSach = tblNhapSach;
        this.jTabbedPane1 = jTabbedPane1;
        ArrayList<NhaCungCapDTO> nccList = NhaCungCapBUS.getInstance().getAll();
        for (NhaCungCapDTO ncc : nccList) {
            if (ncc.getTrangThai() == 1) {
                maNccCbx.addItem(ncc.getMaNCC() + ": " + ncc.getTen());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maNccCbx = new javax.swing.JComboBox<>();
        chooseNccBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chọn nhà cung cấp");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        maNccCbx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maNccCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định" }));

        chooseNccBtn.setText("Đồng ý");
        chooseNccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseNccBtnMouseClicked(evt);
            }
        });

        cancelBtn.setText("Huỷ");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maNccCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(chooseNccBtn)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(maNccCbx)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooseNccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void chooseNccBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseNccBtnMouseClicked
        String maNCC = "";
        if (maNccCbx.getSelectedIndex() > 0) {
            String nccTxt = (String) maNccCbx.getSelectedItem();
            String[] maNCCArray = nccTxt.split(":");
            maNCC = maNCCArray[0];
            tblNhapSach.showIn4ChiTietPhieuNhap(maNCC);
            jTabbedPane1.setSelectedIndex(1);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã nhà cung cấp hợp lệ!", "Chọn NCC thất bại!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_chooseNccBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton chooseNccBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> maNccCbx;
    // End of variables declaration//GEN-END:variables
}
